Refactor: upgrade to ts project
alibaba-fusion/validate pull request #46
Opened 2024-01-24 08:53 UTC by YSMJ1994

2024-01-26 11:59 UTC, eternalsky requested changes

2024-01-26 11:59 UTC, eternalsky commented on src/rules/format.ts
> +function validatorIDNumber(idCode: unknown) {
这里 idCode 为什么是 unknown  呢？从下方的逻辑判断看，必然是 string。

2024-01-26 11:59 UTC, eternalsky commented on src/rules/format.ts
> +    number(value: unknown) {
这里的几处也同样无法理解。

2024-01-26 11:59 UTC, eternalsky commented on src/util.ts
> +import {
这里也没有 import type

2024-01-31 07:42 UTC, YSMJ1994 commented on src/rules/format.ts
> +    number(value: unknown) {
这几个 unknown 代表这几个函数可以传递任意类型的参数，因为下方的代码会首先推断参数类型，即使非预期类型均可以正常返回结果

2024-01-31 08:54 UTC, eternalsky approved these changes

2024-01-31 08:55 UTC, merged